### ISSUE TITLE
Travellers Map Not Saving Waypoints on Exit in Minecraft 1.16.1

### ISSUE THREAD

**Issue by Gryffen1971** [JTK222/Travellers-Map#4]
I currently have Travellers Map installed and i have set waypoints on the map. After playing for about an 1-2 Hours i "Save&Quit".

I return later and enter my saved world and all of my waypoints i created are now gone.
This happens everytime i "Save&Quit" and come back to my world.

I am using;

Minecraft:  1.16.1
Forge:  32.0.47

**Comment by JTK222** [comment]
Ehm, whoops.
As it seems they only don't get loaded though.
Can you check whether you have files in /mod_data/travellers_map/xyz/xyz/waypoints?
If yes, they are not lost. but just don't get loaded.
(I'll try to fix it asap)

**Comment by JTK222** [comment]
Should be fixed in <https://www.curseforge.com/minecraft/mc-mods/travellers-map/files/2999854>
I'd appreciate if you could let me know whether that fixed it for you.
If you don't respond within ~3 days I'll assume it's fixed and close this.
(Although I usually only close issues if new ones are opened and I get reminded that they exist)

**Comment by Gryffen1971** [comment]
Thanks for the Response. I'll download today and report back.
I'll check to see about those files before i update.

**Comment by Gryffen1971** [comment]
I have looked in the directory "/mod_data/travellers-maps/xyz/xyz/waypoints" and yes the "WAYPOINT File(s)" were there.
Also, is it coded to have the name of the Type of File in all caps? or is that just windows causing that?

Just to be clear! I do not blame you for any misstep(s) due to 'IRL' in your creation of the mod. Things do get missed/overlooked because of outside issues in IRL.

**Comment by Gryffen1971** [comment]
Update,

I installed the updated mod and the waypoints now appear on the Map.

If, i may i have an enhancement(s) i would like to suggest. If, at all possible.

1. Waypoint Teleporting while using the map.
2. Death Markers on Map as waypoints to recover inventory Items.

I suggest this because of another Mod "Journey Maps" that had both of these Functions. Please consider theses suggestions.

Again, Thanks for the Quick Response and Update of Mod.

Good Luck and Stay Safe.
